### ISSUE TITLE
All PSoC 6 MCU Examples are now inaccessible

### ISSUE THREAD

**Issue by nburkitt** [Infineon/Code-Examples-for-ModusToolbox-Software#2]
https://github.com/Infineon/Code-Examples-for-ModusToolbox-Software contains a link titled PSoC 6 MCU Examples, to URL https://github.com/cypresssemiconductorco?q=mtb-example-psoc6%20NOT%20Deprecated. 
That page contains only a link to a pinned repository, https://github.com/cypresssemiconductorco/Cypress-is-now-Infineon.
That repository contains only one file, README.md, which contains a single link to URL https://github.com/Infineon.
That page contains a link to a pinned repository, Code-Examples-for-ModusToolbox-Software, to URL https://github.com/Infineon/Code-Examples-for-ModusToolbox-Software, which completes the circular reference back to where we started.

**Comment by cy-vaira** [comment]
Hello, You probably faced that issue when we were in the middle of migration. Now, that [repo ](https://github.com/Infineon/Code-Examples-for-ModusToolbox-Software) is updated with the correct links. Please check again and let us know if you see any issue.
